blank_lines_upper_bound = 2
enum_discrim_align_threshold = 8
struct_field_align_threshold = 8
hard_tabs = true
imports_layout = "HorizontalVertical"
imports_indent = "Visual"
indent_style = "Visual"
match_block_trailing_comma = true
merge_imports = false
reorder_impl_items = true
reorder_imports = true
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 130
