[package]
name = "colorful-gol-rs"
version = "0.1.0"
authors = ["Fun Maker <funmaker95@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.18"
vulkano-shaders = "0.18"
vulkano-win = "0.18"
winit = "0.22"
err-derive = "0.2.3"
getopts = "0.2.21"
